typography_spectrum: 0.7597507396712899
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.024978345958516
  lightness: 0.36766347917728126
  saturation: 0.26768626109696925
  rhythmicContrast: 0.509358010487631
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3820844329893589
analytics:
  google: null
  facebook: null
  twitter: null
name: MyArchingAbroad
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Your Property Finder in Italy
purpose: []
